export { default as Home } from "./Home"
export { default as Rental } from "./Rental"
export { default as OurService } from "./OurService"
export { default as WhyUs } from "./WhyUs"
export { default as Testimonial } from "./Testimonial"
export { default as Faq } from "./Faq"
export { default as Carimobil } from "./Rental"